sudo: required

language: node_js
node_js:
  - "10.2.1"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod --base-href="https://lucasmarchi.github.io/CasaDoCaminhoClient_Angular/"
  - angular-cli-ghpages --no-silent